# Generated by Django 6.0.6 on 2026-06-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_material_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_prevista_devolucion', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado'), ('perdido', 'Perdido')], default='activo', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('profesor_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='LineaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_prestamo', to='inventario.material')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Línea de préstamo',
                'verbose_name_plural': 'Líneas de préstamo',
            },
        ),
    ]
