# Generated by Django 6.0.6 on 2026-06-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario'),
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('fecha_prevista_recogida', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('convertida', 'Convertida en préstamo'), ('cancelada', 'Cancelada'), ('caducada', 'Caducada')], default='activa', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='inventario.material')),
                ('profesor_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_gestionadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
