# Generated by Django 6.0.6 on 2026-06-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        ("ubicaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="ubicacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiales",
                to="ubicaciones.ubicacion",
            ),
        ),
    ]
