# Generated by Django 6.0.6 on 2026-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('retirar', 'Retirar'), ('prestar', 'Prestar'), ('devolver', 'Devolver'), ('reservar', 'Reservar'), ('cancelar_reserva', 'Cancelar reserva'), ('convertir_reserva', 'Convertir reserva'), ('exportar', 'Exportar'), ('acceder', 'Acceder'), ('iniciar_sesion', 'Iniciar sesión'), ('cerrar_sesion', 'Cerrar sesión'), ('login_fallido', 'Login fallido'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
