# Generated by Django 6.0.6 on 2026-06-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0002_material_ubicacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("archivo", models.FileField(upload_to="documentos_material/")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("factura", "Factura"),
                            ("garantia", "Garantía"),
                            ("esquema", "Esquema"),
                            ("fotografia", "Fotografía"),
                            ("proyecto", "Proyecto"),
                            ("configuracion", "Configuración"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=50,
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="inventario.material",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
