# Generated by Django 6.0.6 on 2026-06-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_perfiles_existentes(apps, schema_editor):
    User = apps.get_model("auth", "User")
    PerfilUsuario = apps.get_model("usuarios", "PerfilUsuario")

    for usuario in User.objects.all():
        tipo_usuario = "administrador" if usuario.is_superuser else "profesor"
        PerfilUsuario.objects.get_or_create(
            user=usuario,
            defaults={"tipo_usuario": tipo_usuario},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('profesor', 'Profesor'), ('tecnico', 'Técnico'), ('alumno', 'Alumno')], default='profesor', max_length=20, verbose_name='tipo de usuario')),
                ('departamento', models.CharField(blank=True, max_length=120, verbose_name='departamento')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('puede_recibir_prestamos', models.BooleanField(default=True, verbose_name='puede recibir préstamos')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
        migrations.RunPython(crear_perfiles_existentes, migrations.RunPython.noop),
    ]
