# Generated by Django 6.0.6 on 2026-06-15 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario'),
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=20, verbose_name='tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('frecuencia_dias', models.PositiveIntegerField(default=30, verbose_name='frecuencia en días')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='fecha de inicio')),
                ('proxima_revision', models.DateField(verbose_name='próxima revisión')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_mantenimiento', to='inventario.material', verbose_name='material')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_mantenimiento', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['proxima_revision', 'material__nombre'],
            },
        ),
    ]
