# Generated by Django 6.0.6 on 2026-06-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["edificio__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Edificio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Edificio",
                "verbose_name_plural": "Edificios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Armario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armarios",
                        to="ubicaciones.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Armario",
                "verbose_name_plural": "Armarios",
                "ordering": ["aula__edificio__nombre", "aula__nombre", "nombre"],
                "unique_together": {("aula", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="aula",
            name="edificio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas",
                to="ubicaciones.edificio",
            ),
        ),
        migrations.CreateModel(
            name="Estanteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "armario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estanterias",
                        to="ubicaciones.armario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estantería",
                "verbose_name_plural": "Estanterías",
                "ordering": ["armario__aula__nombre", "armario__nombre", "nombre"],
                "unique_together": {("armario", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "estanteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cajas",
                        to="ubicaciones.estanteria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
                "ordering": ["estanteria__nombre", "nombre"],
                "unique_together": {("estanteria", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicion", models.CharField(blank=True, max_length=100, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "armario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones",
                        to="ubicaciones.armario",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones",
                        to="ubicaciones.aula",
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones",
                        to="ubicaciones.caja",
                    ),
                ),
                (
                    "edificio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones",
                        to="ubicaciones.edificio",
                    ),
                ),
                (
                    "estanteria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones",
                        to="ubicaciones.estanteria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "ordering": [
                    "edificio__nombre",
                    "aula__nombre",
                    "armario__nombre",
                    "estanteria__nombre",
                    "caja__nombre",
                    "posicion",
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="aula",
            unique_together={("edificio", "nombre")},
        ),
    ]
